name: gworf_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - attrs
  - backcall
  - basemap
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cycler
  - cython
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - freetype
  - geos
  - gettext
  - glib
  - healpy
  - icu
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - libblas
  - libcblas
  - libcxx
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - liblapack
  - libpng
  - libsodium
  - llvm-openmp
  - markupsafe
  - matplotlib
  - matplotlib-base
  - metis
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pluggy
  - proj4
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - ptyprocess
  - py
  - pygments
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pyshp
  - pytest
  - pytest-runner
  - python
  - python-dateutil
  - python_abi
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - scikit-sparse
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - suitesparse
  - tbb
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
    - astroplan
    - astropy-healpix
    - cffi
    - cryptography
    - future
    - git+https://github.com/stevertaylor/gworf
    - h5py
    - lalsuite
    - ligo-gracedb
    - ligo-segments
    - ligo-skymap
    - lscsoft-glue
    - networkx
    - pillow
    - ptemcee
    - pycparser
    - pyopenssl
    - python-ligo-lw
    - pyyaml
    - reproject
    - tqdm


