name: gworf_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - astropy=4.0.1.post1
  - attrs=19.3.0
  - backcall=0.1.0
  - basemap=1.2.0
  - blas=1.0
  - bleach=3.1.4
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - cython=0.29.17
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - freetype=2.9.1
  - geos=3.6.2
  - gettext=0.19.8.1
  - glib=2.63.1
  - healpy=1.13.0
  - icu=58.2
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libgfortran=4.0.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvm-openmp=10.0.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - metis=5.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - more-itertools=8.3.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.4
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pluggy=0.13.1
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - py=1.8.1
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pyshp=2.1.0
  - pytest=5.4.3
  - pytest-runner=5.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - scikit-sparse=0.4.4
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.4.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - suitesparse=5.7.2
  - tbb=2019.9
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - astroplan==0.6
    - astropy-healpix==0.5
    - cffi==1.14.0
    - cryptography==2.9.2
    - future==0.18.2
    - git+https://github.com/stevertaylor/gworf
    - h5py==2.10.0
    - lalsuite==6.70
    - ligo-gracedb==2.5.0
    - ligo-segments==1.2.0
    - ligo-skymap==0.3.1
    - lscsoft-glue==2.0.0
    - networkx==2.4
    - pillow==7.1.2
    - ptemcee==1.0.0
    - pycparser==2.20
    - pyopenssl==19.1.0
    - python-ligo-lw==1.6.0
    - pyyaml==5.3.1
    - reproject==0.7.1
    - tqdm==4.46.0

